Diego Yael Islas Santoyo
26/08/2024

# Datos y Numpy


## Problema 1

In [15]:
import pandas as pd

data = {
    'Mes': ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
    'Ingreso': [1340, 2590, 3570, 4450, 1330, 1610, 1500, 2270, 1910, 2120, 3950, 1380],
    'Gasto': [1880, 3130, 2140, 3370, 2990, 1970, 2230, 1240, 1470, 2280, 1870, 3140]
}

df = pd.DataFrame(data)

df['Utilidad'] = df['Ingreso'] - df['Gasto']

gasto_promedio_utilidad_negativa = df[df['Utilidad'] < 0]['Gasto'].mean()

ingresos_totales = df['Ingreso'].sum()

print("DataFrame con Utilidad calculada:")
print(df)
print("\nPromedio de Gastos en meses con Utilidad negativa:")
print(f"${gasto_promedio_utilidad_negativa:.2f}")
print("\nIngresos totales del año:")
print(f"${ingresos_totales:,.2f}")

DataFrame con Utilidad calculada:
           Mes  Ingreso  Gasto  Utilidad
0        Enero     1340   1880      -540
1      Febrero     2590   3130      -540
2        Marzo     3570   2140      1430
3        Abril     4450   3370      1080
4         Mayo     1330   2990     -1660
5        Junio     1610   1970      -360
6        Julio     1500   2230      -730
7       Agosto     2270   1240      1030
8   Septiembre     1910   1470       440
9      Octubre     2120   2280      -160
10   Noviembre     3950   1870      2080
11   Diciembre     1380   3140     -1760

Promedio de Gastos en meses con Utilidad negativa:
$2517.14

Ingresos totales del año:
$28,020.00


## Problema 2

In [23]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

b = np.array([[2],
              [4]])

resultado = np.dot(A, b)

print("Matriz A:")
print(A)
print("\nMatriz b:")
print(b)
print("\nResultado de A*b:")
print(resultado)

Matriz A:
[[1 2]
 [3 4]]

Matriz b:
[[2]
 [4]]

Resultado de A*b:
[[10]
 [22]]
